/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health + readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Walk a folder, detect formats, cluster into strata */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScanRequest"];
                };
            };
            responses: {
                /** @description Scan result with stratum breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strata/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seeded, deterministic stratified sample pick */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SampleRequest"];
                };
            };
            responses: {
                /** @description Sampled docs grouped by stratum */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SampleResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert a single doc with pipeline params, sync */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConvertRequest"];
                };
            };
            responses: {
                /** @description Conversion complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocMeta"];
                    };
                };
                /** @description Parse error or convert failure */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doc metadata by source_sha256 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Doc meta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocMeta"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw source bytes (octet-stream) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Source bytes with correct Content-Type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}/md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markdown export */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Markdown body */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/markdown": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DoclingDocument JSON export */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description DoclingDocument JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DoclingDocument"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markdown ↔ DoclingDocument element map (sidecar) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Anchor map for bidirectional highlight */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Anchor"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{hash}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-convert a doc with different pipeline params */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PipelineParams"];
                };
            };
            responses: {
                /** @description New conversion complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocMeta"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a batch run using a stratum→pipeline map */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchRequest"];
                };
            };
            responses: {
                /** @description Batch job accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch progress (1Hz poll cadence) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current job state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live progress via Server-Sent Events (optional; polling is the fallback) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream of Job deltas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop claiming new jobs; finish in-flight; return final state */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current manifest for the active output folder */
        get: {
            parameters: {
                query: {
                    output_dir: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Manifest */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manifest"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taste_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new taste session for a scanned folder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TasteSessionCreate"];
                };
            };
            responses: {
                /** @description New session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TasteSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taste_sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rehydrate a session's full state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TasteSession"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update approvals / pipeline assignments / lock status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TasteSessionPatch"];
                };
            };
            responses: {
                /** @description Updated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TasteSession"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an export job (manifest-only | manifest+md | full archive) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportRequest"];
                };
            };
            responses: {
                /** @description Export job accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export job progress / result path */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current export state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            detail?: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "not_ready";
            docling_version: string;
            model_ready: boolean;
            /** @description 0.0–1.0 during warmup */
            model_download_progress?: number | null;
            tesseract_present: boolean;
            poppler_present: boolean;
            free_disk_gb?: number;
        };
        ScanRequest: {
            /** @description Absolute local path */
            folder: string;
            /** @default false */
            follow_symlinks: boolean;
            /** @default 50000 */
            max_files: number;
        };
        ScanResult: {
            scan_id: string;
            folder: string;
            total_files: number;
            strata: components["schemas"]["Stratum"][];
            skipped: {
                path: string;
                /** @description e.g. "tier3_audio", "symlink_denied", "unreadable" */
                reason: string;
            }[];
        };
        Stratum: {
            /** @description e.g. pdf-native-11-50, docx, xlsx */
            name: string;
            size: number;
            /** @description min(N, size) — exhaustive if size ≤ 6 */
            sample_size_hint: number;
            /** @description true when size ≤ 6 */
            exhaustive?: boolean;
            /** @description First few filenames, for UI preview */
            example_paths: string[];
        };
        SampleRequest: {
            scan_id: string;
            /** @default 5 */
            n: number;
            /** @description Optional; deterministic resampling */
            seed?: number;
            /** @description Already-approved/rejected hashes to skip */
            exclude_hashes?: string[];
        };
        SampleResult: {
            seed: number;
            strata: {
                name: string;
                docs: components["schemas"]["DocRef"][];
            }[];
        };
        DocRef: {
            source_sha256: string;
            source_path: string;
            /** @description pdf, docx, xlsx, pptx, html, txt, md, latex */
            source_format: string;
            size_bytes?: number;
            page_count?: number | null;
        };
        PipelineParams: {
            ocr?: {
                /** @default true */
                enabled: boolean;
                /**
                 * @default tesseract
                 * @enum {string}
                 */
                engine: "tesseract" | "rapidocr";
            };
            vlm?: {
                /** @default false */
                enabled: boolean;
                /** @default granite_docling */
                model: string;
            };
            tables?: {
                /** @default true */
                enabled: boolean;
            };
            enrichments?: {
                /** @default false */
                formulas: boolean;
                /** @default false */
                code: boolean;
                /** @default false */
                charts: boolean;
            };
        };
        ConvertRequest: {
            source_path: string;
            /** @description Root dir; doc lands at output_dir/<hash>/ */
            output_dir?: string;
            pipeline?: components["schemas"]["PipelineParams"];
        };
        BatchRequest: {
            scan_id: string;
            output_dir: string;
            /** @default 2 */
            concurrency: number;
            /** @description Per-stratum pipeline assignments from the locked taste session */
            stratum_pipelines: {
                stratum: string;
                pipeline: components["schemas"]["PipelineParams"];
            }[];
        };
        Job: {
            id: string;
            /** @enum {string} */
            kind: "batch" | "export";
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "cancelled" | "failed";
            progress: {
                docs_total?: number;
                docs_done?: number;
                docs_failed?: number;
                docs_per_sec?: number;
                eta_seconds?: number | null;
                per_stratum?: {
                    name?: string;
                    total?: number;
                    done?: number;
                    failed?: number;
                }[];
            };
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            error?: string | null;
            /** @description For exports: path to artifact */
            result_path?: string | null;
        };
        QualityBadge: {
            page: number;
            /** @enum {string} */
            kind: "ocr_low" | "empty_page" | "table_warn" | "figure_missing" | "parse_warning";
            /** @description e.g. OCR conf 0.62 */
            value?: number | null;
            message?: string | null;
        };
        DocMeta: {
            source_sha256: string;
            source_path: string;
            source_format: string;
            docling_version: string;
            pipeline_params: components["schemas"]["PipelineParams"];
            /** @description Hash of pipeline_params; differentiates rerun outputs */
            pipeline_hash: string;
            runtime_ms: number;
            /** @enum {string} */
            status: "ok" | "partial" | "error";
            error?: string | null;
            stats?: {
                page_count?: number;
                text_element_count?: number;
                table_count?: number;
                picture_count?: number;
                md_char_count?: number;
                json_size_bytes?: number;
            };
            quality_signals?: {
                ocr_confidence_per_page?: number[];
                empty_pages?: number[];
                warnings?: components["schemas"]["QualityBadge"][];
            };
            /** Format: date-time */
            converted_at?: string;
        };
        /** @description Sidecar entry mapping MD byte range ↔ DoclingDocument element */
        Anchor: {
            /** @description e.g. "#/texts/42" */
            self_ref: string;
            byte_start: number;
            byte_end: number;
            page: number;
            /** @description text, section_header, table, picture, list_item, etc. */
            label: string;
            bbox?: components["schemas"]["BBox"];
        };
        BBox: {
            l: number;
            t: number;
            r: number;
            b: number;
            /** @enum {string} */
            coord_origin: "BOTTOMLEFT" | "TOPLEFT";
        };
        ManifestEntry: {
            source_sha256: string;
            source_path: string;
            source_format: string;
            /** @enum {string} */
            status: "pending" | "processing" | "complete" | "error" | "skipped";
            stratum: string;
            pipeline_hash: string;
            error?: string | null;
            quality_summary?: {
                ocr_avg?: number | null;
                warning_count?: number;
                empty_page_count?: number;
            };
            /** Format: date-time */
            converted_at?: string | null;
        };
        Manifest: {
            /** @default 1 */
            schema_version: number;
            folder_root: string;
            output_dir: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            docling_version?: string;
            docs: components["schemas"]["ManifestEntry"][];
        };
        TasteSessionCreate: {
            scan_id: string;
            output_dir: string;
        };
        DocApproval: {
            source_sha256: string;
            /** @enum {string} */
            status: "approved" | "rejected" | "skipped" | "flagged";
            notes?: string | null;
            /** Format: date-time */
            reviewed_at: string;
            /** @description Pipeline under which this doc was reviewed */
            pipeline_hash?: string;
        };
        StratumState: {
            name: string;
            size: number;
            pipeline: components["schemas"]["PipelineParams"];
            approvals: components["schemas"]["DocApproval"][];
            locked: boolean;
            /** @enum {string} */
            status: "under_review" | "converged" | "non_convergent" | "exhausted";
        };
        TasteSession: {
            id: string;
            folder_root: string;
            output_dir: string;
            scan_id: string;
            strata: components["schemas"]["StratumState"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Monotonic; used for PATCH optimistic locking */
            version?: number;
        };
        TasteSessionPatch: {
            /** @description Current session version for CAS */
            version: number;
            /** @description Add or update an approval */
            approval?: {
                stratum?: string;
                approval?: components["schemas"]["DocApproval"];
            };
            /** @description Set a stratum pipeline */
            pipeline_assignment?: {
                stratum?: string;
                pipeline?: components["schemas"]["PipelineParams"];
            };
            /** @description Lock a stratum (commits pipeline for batch) */
            lock_stratum?: {
                stratum?: string;
                locked?: boolean;
            };
        };
        ExportRequest: {
            output_dir: string;
            /** @enum {string} */
            kind: "manifest_only" | "manifest_plus_md" | "full_archive";
            /** @description Absolute file or directory path */
            destination: string;
        };
        /**
         * @description Minimal surface the frontend uses; full schema is whatever
         *     Docling 2.90.0 emits and is documented upstream.
         */
        DoclingDocument: {
            schema_name?: string;
            version?: string;
            name?: string;
            pages?: {
                [key: string]: {
                    page_no?: number;
                    size?: {
                        width?: number;
                        height?: number;
                    };
                };
            };
            texts?: components["schemas"]["DoclingItem"][];
            tables?: components["schemas"]["DoclingItem"][];
            pictures?: components["schemas"]["DoclingItem"][];
        };
        DoclingItem: {
            self_ref?: string;
            label?: string;
            text?: string;
            prov?: components["schemas"]["Provenance"][];
        };
        Provenance: {
            page_no?: number;
            bbox?: components["schemas"]["BBox"];
            charspan?: number[];
        };
    };
    responses: {
        /** @description Request validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
